# Generated by Django 5.2 on 2025-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_author_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
